name: checks
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install CMSimple_XH
        run: |
          curl -fsSL -o CMSimple_XH-1.7.5.zip https://github.com/cmsimple-xh/cmsimple-xh/releases/download/1.7.5/CMSimple_XH-1.7.5.zip
          unzip -q CMSimple_XH-1.7.5.zip
      - name: Checkout Schedule_XH
        uses: actions/checkout@v2
        with:
          path: 'cmsimplexh/plugins/schedule'
      - name: composer install
        run: cd cmsimplexh/plugins/schedule && composer install
      - name: phing sniff
        run: cd cmsimplexh/plugins/schedule && PATH=vendor/bin:$PATH phing sniff
      - name: phing mess
        run: cd cmsimplexh/plugins/schedule && PATH=vendor/bin:$PATH phing mess
      - name: phing stan
        run: cd cmsimplexh/plugins/schedule && PATH=vendor/bin:$PATH phing stan
      - name: phing test
        run: cd cmsimplexh/plugins/schedule && PATH=vendor/bin:$PATH phing test
